# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBXT3VU4UTvuAjmMeXw4XVoA52tPjIdo
"""

score_list=input().split( )
count=0
for i in score_list:
  if int(i) <60:
    count+=1
print("不及格人數:"+str(count))
max=score_list[0]
min=score_list[0]
for i in score_list:
  if i>max:
    max=i
  elif i<min:
    min=i
print("最大值為:"+max,"最小值為:"+min)