# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DClffbyRLIXTvO7fs1EaEh_9k1Hiz15W
"""

score_list = input().split()
count=0
total=0

for i in score_list:
    score = int(i)
    total += score
    if score < 60:
        count += 1

average= total/len(score_list)

print(count)
print(int(average))